export type Language = "EN" | "HI" | "KA" | "TA" | "TE" | "ML";

export const translations = {
  EN: {
    title: "CivicGuide AI",
    tagline: "Elections Reimagined with AI",
    heroTitle: "Your Guide to Digital Democracy.",
    heroSubtitle: "Navigate the Indian election process with confidence. CivicGuide AI provides personalized timelines, AI-driven candidate insights, and verified voting guidance.",
    getStarted: "Get Started",
    askAI: "Ask AI Assistant",
    timeline: "Timeline",
    candidates: "Candidates",
    simulator: "Simulator",
    chatbot: "AI Assistant",
    quiz: "Quiz",
    fakeNews: "Fact Check",
    home: "Home",
  },
  HI: {
    title: "सिविकगाइड AI",
    tagline: "AI के साथ चुनावों का नया स्वरूप",
    heroTitle: "डिजिटल लोकतंत्र के लिए आपका मार्गदर्शक।",
    heroSubtitle: "भारतीय चुनाव प्रक्रिया को आत्मविश्वास के साथ समझें। सिविकगाइड AI व्यक्तिगत समयरेखा, AI-संचालित उम्मीदवार अंतर्दृष्टि और सत्यापित मतदान मार्गदर्शन प्रदान करता है।",
    getStarted: "शुरू करें",
    askAI: "AI सहायक से पूछें",
    timeline: "समयरेखा",
    candidates: "उम्मीदवार",
    simulator: "सिम्युलेटर",
    chatbot: "AI सहायक",
    quiz: "प्रश्नोत्तरी",
    fakeNews: "तथ्य जाँच",
    home: "होम",
  },
  KA: {
    title: "ಸಿವಿಕ್‌ಗೈಡ್ AI",
    tagline: "AI ನೊಂದಿಗೆ ಚುನಾವಣೆಗಳ ಮರುಕಲ್ಪನೆ",
    heroTitle: "ಡಿಜಿಟಲ್ ಪ್ರಜಾಪ್ರಭುತ್ವಕ್ಕೆ ನಿಮ್ಮ ಮಾರ್ಗದರ್ಶಿ.",
    heroSubtitle: "ಭಾರತೀಯ ಚುನಾವಣಾ ಪ್ರಕ್ರಿಯೆಯನ್ನು ಆತ್ಮವಿಶ್ವಾಸದಿಂದ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ. ಸಿವಿಕ್‌ಗೈಡ್ AI ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ವೇಳಾಪಟ್ಟಿಗಳು, AI-ಚಾಲಿತ ಅಭ್ಯರ್ಥಿಗಳ ಒಳನೋಟಗಳು ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ಮತದಾನ ಮಾರ್ಗದರ್ಶನವನ್ನು ಒದಗಿಸುತ್ತದೆ.",
    getStarted: "ಪ್ರಾರಂಭಿಸಿ",
    askAI: "AI ಸಹಾಯಕರನ್ನು ಕೇಳಿ",
    timeline: "ವೇಳಾಪಟ್ಟಿ",
    candidates: "ಅಭ್ಯರ್ಥಿಗಳು",
    simulator: "ಸಿಮ್ಯುಲೇಟರ್",
    chatbot: "AI ಸಹಾಯಕ",
    quiz: "ರಸಪ್ರಶ್ನೆ",
    fakeNews: "ಸತ್ಯಶೋಧನೆ",
    home: "ಮುಖಪುಟ",
  },
  TA: {
    title: "സിവിക് കൈഡ് AI",
    tagline: "AI மூலம் தேர்தல்கள் மறுவடிவமைப்பு",
    heroTitle: "டிஜிட்டல் ஜனநாயகத்திற்கான உங்கள் வழிகாட்டி.",
    heroSubtitle: "இந்திய தேர்தல் செயல்முறையை நம்பிக்கையுடன் அணுகுங்கள். சிசிவிக் கைடு AI தனிப்பயனாக்கப்பட்ட காலக்கெடு, AI மூலம் வேட்பாளர் விவரங்கள் மற்றும் சரிபார்க்கப்பட்ட வாக்கு வழிகாட்டுதலை வழங்குகிறது.",
    getStarted: "தொடங்கவும்",
    askAI: "AI உதவியாளரிடம் கேளுங்கள்",
    timeline: "காலவரிசை",
    candidates: "வேட்பாளர்கள்",
    simulator: "சிமுலேட்டர்",
    chatbot: "AI உதவியாளர்",
    quiz: "வினாடி வினா",
    fakeNews: "உண்மை சரிபார்ப்பு",
    home: "முகப்பு",
  },
  TE: {
    title: "సివిక్ గైడ్ AI",
    tagline: "AI తో ఎన్నికల కొత్త రూపం",
    heroTitle: "డిజిటల్ ప్రజాస్వామ్యానికి మీ మార్గదర్శి.",
    heroSubtitle: "భారతీయ ఎన్నికల ప్రక్రియను ఆత్మవిశ్వాసంతో అర్థం చేసుకోండి. సివిక్ గైడ్ AI వ్యక్తిగతీకరించిన సమయపాలన, AI ఆధారిత అభ్యర్థుల సమాచారం మరియు ధృవీకరించబడిన ఓటింగ్ మార్గదర్శకత్వాన్ని అందిస్తుంది.",
    getStarted: "ప్రారంభించండి",
    askAI: "AI సహాయకుడిని అడగండి",
    timeline: "సమయపాలన",
    candidates: "అభ్యర్థులు",
    simulator: "సిమ్యులేటర్",
    chatbot: "AI సహాయకుడు",
    quiz: "క్విజ్",
    fakeNews: "నిజ నిర్ధారణ",
    home: "హోమ్",
  },
  ML: {
    title: "സിവിക് ഗൈഡ് AI",
    tagline: "AI ഉപയോഗിച്ച് തിരഞ്ഞെടുപ്പുകൾ വീണ്ടും വിഭാവനം ചെയ്യുക",
    heroTitle: "ഡിജിറ്റൽ ജനാധിപത്യത്തിലേക്കുള്ള നിങ്ങളുടെ വഴികാട്ടി.",
    heroSubtitle: "ഇന്ത്യൻ തിരഞ്ഞെടുപ്പ് പ്രക്രിയ ആത്മവിശ്വാസത്തോടെ മനസ്സിലാക്കൂ. സിവിക് ഗൈഡ് AI വ്യക്തിഗതമാക്കിയ സമയക്രമം, AI അടിസ്ഥാനമാക്കിയുള്ള സ്ഥാനാർത്ഥി വിവരങ്ങൾ, പരിശോധിച്ച വോട്ടിംഗ് മാർഗ്ഗനിർദ്ദേശം എന്നിവ നൽകുന്നു.",
    getStarted: "ആരംഭിക്കുക",
    askAI: "AI അസിസ്റ്റന്റിനോട് ചോദിക്കൂ",
    timeline: "സമയക്രമം",
    candidates: "സ്ഥാനാർത്ഥികൾ",
    simulator: "സിമുലേറ്റർ",
    chatbot: "AI അസിസ്റ്റന്റ്",
    quiz: "ക്വിസ്",
    fakeNews: "വസ്തുതാ പരിശോധന",
    home: "ഹോം",
  }
};
